version: '3.8'

services:
  web:
    build:
      context: .
    container_name: flask_web
    ports:
      - "5000:5000"
    environment:
      - APP_MESSAGE=Hello from Compose!
      - DB_HOST=db
      - DB_PORT=5432
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:

